### ISSUE TITLE
R wrapper for Ukkonen's suffix tree implementation

### ISSUE THREAD

**Issue by loneharoon** [abahgat/suffixtree#4]
I want to use your suffix tree implementation in R using rJava package. I am particularly interested in this because there is no existing native R implementation of this.  So, I am planning to develop a wrapper package in R for this Java implementation, so that both me and others can use it.

 In regard of this, I need your help in understanding the code in more detail. I have understood Suffix tree concepts from http://stackoverflow.com/questions/9452701/ukkonens-suffix-tree-algorithm-in-plain-english.  Currently, I am focussing on put and search methods. My doubt is - 
     Why we use index with put method. Suppose I want to insert 3 strings/patterns: 'ababsbsdeg', 'djejdhee', 'dkrhrhrl'.  How should I decide the indexes while inserting these three patterns into suffix tree

**Comment by abahgat** [comment]
Hi Aroon,
when I wrote the implementation in this repository the problem I was planning on using this suffix tree to index a collection of objects (stored in an array-like structure) using strings as keys to the suffix tree.
The index that I'd pass as a second argument to `put` would be a reference to the index of the object being indexed in the array-like structure that contained all the objects.

If I understand your example, assuming you would want to search for a string an know which of the three inputs were to contain it, you could do this:

```java
String[] strings = new String[] {'ababsbsdeg', 'djejdhee', 'dkrhrhrl'};
for (int i = 0; i < strings.length; ++i) {
  tree.put(strings[i], i);
}
```

Hope this helps,
Alessandro
